crab report -d crab_projects/crab_Tau3mu_reco2023_RunB_stream0_Mini_v3
crab report -d crab_projects/crab_Tau3mu_reco2023_RunB_stream1_Mini_v3
crab report -d crab_projects/crab_Tau3mu_reco2023_RunB_stream2_Mini_v3
crab report -d crab_projects/crab_Tau3mu_reco2023_RunB_stream3_Mini_v3
crab report -d crab_projects/crab_Tau3mu_reco2023_RunB_stream4_Mini_v3
crab report -d crab_projects/crab_Tau3mu_reco2023_RunB_stream5_Mini_v3
crab report -d crab_projects/crab_Tau3mu_reco2023_RunB_stream6_Mini_v3
crab report -d crab_projects/crab_Tau3mu_reco2023_RunB_stream7_Mini_v3
